# -*- coding: utf-8 -*-
"""boundcrs_compound.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WuG4iGoCuIATSaWLq4039C8Ctkt2WQOG

Example of creating a Compound BoundCRS with pyproj
"""

import os
import sys

!pip install pyproj

import pyproj

pyproj.__version__

pyproj.proj_version_str

pyproj.network.set_network_enabled(active=True)

source_crs_wkt = 'COMPOUNDCRS["NAD83 / UTM zone 15N + NOAA Chart Datum",PROJCRS["NAD83 / UTM zone 15N",BASEGEOGCRS["NAD83",DATUM["North American Datum 1983",ELLIPSOID["GRS 1980",6378137,298.257222101,LENGTHUNIT["metre",1]]],PRIMEM["Greenwich",0,ANGLEUNIT["degree",0.0174532925199433]],ID["EPSG",4269]],CONVERSION["UTM zone 15N",METHOD["Transverse Mercator",ID["EPSG",9807]],PARAMETER["Latitude of natural origin",0,ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8801]],PARAMETER["Longitude of natural origin",-93,ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8802]],PARAMETER["Scale factor at natural origin",0.9996,SCALEUNIT["unity",1],ID["EPSG",8805]],PARAMETER["False easting",500000,LENGTHUNIT["metre",1],ID["EPSG",8806]],PARAMETER["False northing",0,LENGTHUNIT["metre",1],ID["EPSG",8807]]],CS[Cartesian,2],AXIS["(E)",east,ORDER[1],LENGTHUNIT["metre",1]],AXIS["(N)",north,ORDER[2],LENGTHUNIT["metre",1]],USAGE[SCOPE["Engineering survey, topographic mapping."],AREA["North America - between 96°W and 90°W - onshore and offshore. Canada - Manitoba; Nunavut; Ontario. United States (USA) - Arkansas; Illinois; Iowa; Kansas; Louisiana; Michigan; Minnesota; Mississippi; Missouri; Nebraska; Oklahoma; Tennessee; Texas; Wisconsin."],BBOX[25.61,-96,84,-90]],ID["EPSG",26915]],VERTCRS["NOAA Chart Datum",VDATUM["NOAA Chart Datum"],CS[vertical,1],AXIS["gravity-related height (H)",up,LENGTHUNIT["metre",1,ID["EPSG",9001]]]]]'
source_crs = pyproj.CRS.from_wkt(source_crs_wkt)

target_crs = pyproj.CRS('EPSG:6344').to_3d()

"""We need the files to reference for making the transformation will pull via FTP for this example."""

from ftplib import FTP
from zipfile import ZipFile
with FTP('ocsftp.ncd.noaa.gov') as ocs_ftp:
  ocs_ftp.login()
  ocs_ftp.cwd('HSTB')
  with open('vdatum.zip', 'wb') as vdatum_zip:
    ocs_ftp.retrbinary('RETR vdatum.zip', vdatum_zip.write)
with ZipFile('vdatum.zip') as vdatum:
  vdatum.extractall()
pyproj.datadir.append_data_dir('vdatum')

pipeline_str = 'proj=pipeline inv step proj=vgridshift grids=core/geoid12b/g2012bu0.gtx step proj=vgridshift grids=TXlaggal01_8301/tss.gtx inv step proj=vgridshift grids=TXlaggal01_8301/mllw.gtx'
mllw_to_NAD83 = pyproj.Transformer.from_pipeline(pipeline_str)

coop_json = {}
coop_json['$schema'] = target_crs.to_json_dict()['$schema']
coop_json['type'] = 'Transformation'
coop_json['name'] = 'MLLW to NAD83(2011)'
coop_json['source_crs'] = source_crs.to_json_dict()
coop_json['target_crs'] = target_crs.to_json_dict()
coop_json['method'] = mllw_to_NAD83.to_json_dict()['method']
params = [{'name': 'Geoid (height correction) model file', 'value': 'core\\geoid12b\\g2012bu0.gtx'},
 {'name': 'TSS (height correction) model file', 'value': 'TXlaggal01_8301\\tss.gtx'},
 {'name': 'MLLW (height correction) model file', 'value': 'TXlaggal01_8301\\mllw.gtx'}]
coop_json['parameters'] = params
coop = pyproj.crs.CoordinateOperation.from_json_dict(coop_json)

mllw_as_boundcrs = pyproj.crs.BoundCRS(source_crs, target_crs, coop)
print(mllw_as_boundcrs.to_wkt(version='WKT2_2019', pretty=True))

"""
BOUNDCRS[
    SOURCECRS[
        COMPOUNDCRS["NAD83 / UTM zone 15N + NOAA Chart Datum",
            PROJCRS["NAD83 / UTM zone 15N",
                BASEGEOGCRS["NAD83",
                    DATUM["North American Datum 1983",
                        ELLIPSOID["GRS 1980",6378137,298.257222101,
                            LENGTHUNIT["metre",1]]],
                    PRIMEM["Greenwich",0,
                        ANGLEUNIT["degree",0.0174532925199433]],
                    ID["EPSG",4269]],
                CONVERSION["UTM zone 15N",
                    METHOD["Transverse Mercator",
                        ID["EPSG",9807]],
                    PARAMETER["Latitude of natural origin",0,
                        ANGLEUNIT["degree",0.0174532925199433],
                        ID["EPSG",8801]],
                    PARAMETER["Longitude of natural origin",-93,
                        ANGLEUNIT["degree",0.0174532925199433],
                        ID["EPSG",8802]],
                    PARAMETER["Scale factor at natural origin",0.9996,
                        SCALEUNIT["unity",1],
                        ID["EPSG",8805]],
                    PARAMETER["False easting",500000,
                        LENGTHUNIT["metre",1],
                        ID["EPSG",8806]],
                    PARAMETER["False northing",0,
                        LENGTHUNIT["metre",1],
                        ID["EPSG",8807]]],
                CS[Cartesian,2],
                    AXIS["(E)",east,
                        ORDER[1],
                        LENGTHUNIT["metre",1]],
                    AXIS["(N)",north,
                        ORDER[2],
                        LENGTHUNIT["metre",1]],
                ID["EPSG",26915]],
            VERTCRS["NOAA Chart Datum",
                VDATUM["NOAA Chart Datum"],
                CS[vertical,1],
                    AXIS["gravity-related height (H)",up,
                        LENGTHUNIT["metre",1,
                            ID["EPSG",9001]]]]]],
    TARGETCRS[
        PROJCRS["NAD83(2011) / UTM zone 15N",
            BASEGEOGCRS["NAD83(2011)",
                DATUM["NAD83 (National Spatial Reference System 2011)",
                    ELLIPSOID["GRS 1980",6378137,298.257222101,
                        LENGTHUNIT["metre",1]]],
                PRIMEM["Greenwich",0,
                    ANGLEUNIT["degree",0.0174532925199433]],
                ID["EPSG",6319]],
            CONVERSION["UTM zone 15N",
                METHOD["Transverse Mercator",
                    ID["EPSG",9807]],
                PARAMETER["Latitude of natural origin",0,
                    ANGLEUNIT["degree",0.0174532925199433],
                    ID["EPSG",8801]],
                PARAMETER["Longitude of natural origin",-93,
                    ANGLEUNIT["degree",0.0174532925199433],
                    ID["EPSG",8802]],
                PARAMETER["Scale factor at natural origin",0.9996,
                    SCALEUNIT["unity",1],
                    ID["EPSG",8805]],
                PARAMETER["False easting",500000,
                    LENGTHUNIT["metre",1],
                    ID["EPSG",8806]],
                PARAMETER["False northing",0,
                    LENGTHUNIT["metre",1],
                    ID["EPSG",8807]],
                ID["EPSG",16015]],
            CS[Cartesian,3],
                AXIS["(E)",east,
                    ORDER[1],
                    LENGTHUNIT["metre",1,
                        ID["EPSG",9001]]],
                AXIS["(N)",north,
                    ORDER[2],
                    LENGTHUNIT["metre",1,
                        ID["EPSG",9001]]],
                AXIS["ellipsoidal height (h)",up,
                    ORDER[3],
                    LENGTHUNIT["metre",1,
                        ID["EPSG",9001]]],
            USAGE[
                SCOPE["unknown"],
                AREA["United States (USA) - between 96°W and 90°W onshore and offshore - Arkansas; Illinois; Iowa; Kansas; Louisiana; Michigan; Minnesota; Mississippi; Missouri; Nebraska; Oklahoma; Tennessee; Texas; Wisconsin."],
                BBOX[25.61,-96.01,49.38,-90]],
            REMARK["Promoted to 3D from EPSG:6344"]]],
    ABRIDGEDTRANSFORMATION["MLLW to NAD83(2011)",
        METHOD["PROJ-based operation method: proj=pipeline inv step proj=vgridshift grids=core/geoid12b/g2012bu0.gtx step proj=vgridshift grids=TXlaggal01_8301/tss.gtx inv step proj=vgridshift grids=TXlaggal01_8301/mllw.gtx"],
        PARAMETERFILE["Geoid (height correction) model file","core\geoid12b\g2012bu0.gtx"],
        PARAMETERFILE["TSS (height correction) model file","TXlaggal01_8301\tss.gtx"],
        PARAMETERFILE["MLLW (height correction) model file","TXlaggal01_8301\mllw.gtx"]]]
"""